global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoPopupXamlApp.DataContracts;
global using UnoPopupXamlApp.DataContracts.Serialization;
global using UnoPopupXamlApp.Models;
global using UnoPopupXamlApp.Presentation;
global using UnoPopupXamlApp.Services.Caching;
global using UnoPopupXamlApp.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
